// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using No.API.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace No.API.Migrations
{
    [DbContext(typeof(NoContext))]
    partial class NoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("No.API.Entities.Letter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("WritedAt")
                        .HasColumnType("DATE");

                    b.HasKey("Id");

                    b.HasIndex("WritedAt")
                        .IsUnique();

                    b.ToTable("Letter");
                });
#pragma warning restore 612, 618
        }
    }
}
